-- ============================================================
-- Supply Chain Management System - Module 1 (Login Dashboard)
-- Database: Oracle XE 21.3
-- ============================================================
-- Run this as SYS or SYSTEM (e.g. in SQL*Plus, SQLcl, or SQL Developer)
-- connected to the CDB, or adjust to run inside XEPDB1 directly.
-- ============================================================

-- Step 1: create a dedicated schema/user for the app
-- (skip this block if scms_user already exists)
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER scms_user IDENTIFIED BY scms_pass;
GRANT CONNECT, RESOURCE TO scms_user;
GRANT CREATE SESSION TO scms_user;
ALTER USER scms_user QUOTA UNLIMITED ON USERS;

-- Step 2: connect as scms_user before running the rest
-- (in SQL*Plus:  CONNECT scms_user/scms_pass@localhost:1521/XEPDB1)

CREATE TABLE users (
    user_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(50)  NOT NULL UNIQUE,
    password     VARCHAR2(256) NOT NULL,          -- SHA-256 hashed password
    full_name    VARCHAR2(100) NOT NULL,
    email        VARCHAR2(100),
    role         VARCHAR2(30)  NOT NULL
                 CHECK (role IN ('ADMIN','PROCUREMENT_MANAGER','WAREHOUSE_MANAGER',
                                  'SUPPLIER','LOGISTICS_STAFF')),
    status       VARCHAR2(10) DEFAULT 'ACTIVE'
                 CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Sample users (password for ALL of them is: Passw0rd!)
-- SHA-256("Passw0rd!") =
-- e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee
-- (generated by PasswordUtil.hashPassword; see util package)
-- ============================================================
INSERT INTO users (username, password, full_name, email, role) VALUES
('admin1',       'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'System Administrator', 'admin@scms.com',        'ADMIN');
INSERT INTO users (username, password, full_name, email, role) VALUES
('proc_mgr1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Ravi Kumar',           'proc@scms.com',         'PROCUREMENT_MANAGER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('wh_mgr1',      'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Suresh Babu',          'warehouse@scms.com',    'WAREHOUSE_MANAGER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('supplier1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'ABC Traders Pvt Ltd',  'supplier@scms.com',     'SUPPLIER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('logistics1',   'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Karthik Raja',         'logistics@scms.com',    'LOGISTICS_STAFF');

COMMIT;

-- ============================================================
-- Module 2 (Supplier Management)
-- SRS section 6 - Supplier_ID, Supplier_Name, Contact_No, Email, Address
-- ============================================================

CREATE TABLE suppliers (
    supplier_id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    supplier_name  VARCHAR2(150) NOT NULL,
    contact_no     VARCHAR2(20)  NOT NULL,
    email          VARCHAR2(100),
    address        VARCHAR2(255),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample suppliers
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('ABC Traders Pvt Ltd',   '9876543210', 'contact@abctraders.com',    'No. 12, Anna Salai, Chennai');
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('Global Steel Supplies', '9123456780', 'sales@globalsteel.com',     'Plot 7, Industrial Estate, Coimbatore');
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('Prime Packaging Co.',   '9988776655', 'info@primepackaging.com',   '45 Market Road, Madurai');

COMMIT;

-- ============================================================
-- Module 3 (Procurement Management) - Purchase Orders
-- PO-01 Create, PO-02 Approve, PO-03 Cancel, PO-04 Track Status,
-- PO-05 Supplier Performance, PO-06 Reports
-- ============================================================

CREATE TABLE purchase_orders (
    po_id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    supplier_id    NUMBER NOT NULL REFERENCES suppliers(supplier_id),
    item_name      VARCHAR2(150) NOT NULL,
    quantity       NUMBER(10)     NOT NULL,
    unit_price     NUMBER(12,2)   NOT NULL,
    total_amount   NUMBER(14,2)   NOT NULL,
    status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
                   CONSTRAINT chk_po_status
                   CHECK (status IN ('PENDING','APPROVED','SHIPPED','CANCELLED','COMPLETED')),
    created_by     VARCHAR2(50),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by    VARCHAR2(50),
    approved_at    TIMESTAMP,
    shipped_at     TIMESTAMP,
    delivered_at   TIMESTAMP,
    remarks        VARCHAR2(255)
);

-- Sample purchase orders
INSERT INTO purchase_orders (supplier_id, item_name, quantity, unit_price, total_amount, status, created_by) VALUES
(1, 'Steel Rods (12mm)', 500, 65.00, 32500.00, 'APPROVED', 'admin1');
INSERT INTO purchase_orders (supplier_id, item_name, quantity, unit_price, total_amount, status, created_by) VALUES
(2, 'Packaging Boxes',   2000, 12.50, 25000.00, 'PENDING', 'proc_mgr1');
INSERT INTO purchase_orders (supplier_id, item_name, quantity, unit_price, total_amount, status, created_by) VALUES
(3, 'Industrial Gloves', 1000, 45.00, 45000.00, 'CANCELLED', 'proc_mgr1');

COMMIT;

-- ============================================================
-- Links a SUPPLIER-role login to the supplier company record they
-- represent, so the Supplier Portal (below) knows whose orders to show.
-- NULL for every other role.
-- ============================================================

ALTER TABLE users ADD supplier_id NUMBER REFERENCES suppliers(supplier_id);

UPDATE users SET supplier_id = (SELECT supplier_id FROM suppliers WHERE supplier_name = 'ABC Traders Pvt Ltd')
WHERE username = 'supplier1';

COMMIT;

-- ============================================================
-- MIGRATING AN EXISTING DATABASE (skip this if running the whole
-- script fresh -- the CREATE TABLE and ALTER TABLE statements above
-- already include everything below).
--
-- If you already ran an earlier version of this script and
-- purchase_orders / users already exist, run this instead:
--
--   ALTER TABLE purchase_orders ADD shipped_at TIMESTAMP;
--   ALTER TABLE purchase_orders ADD delivered_at TIMESTAMP;
--   SELECT constraint_name FROM user_constraints
--     WHERE table_name = 'PURCHASE_ORDERS' AND constraint_type = 'C';
--   ALTER TABLE purchase_orders DROP CONSTRAINT <name_from_above>;
--   ALTER TABLE purchase_orders ADD CONSTRAINT chk_po_status
--     CHECK (status IN ('PENDING','APPROVED','SHIPPED','CANCELLED','COMPLETED'));
--   ALTER TABLE users ADD supplier_id NUMBER REFERENCES suppliers(supplier_id);
--   UPDATE users SET supplier_id = (SELECT supplier_id FROM suppliers WHERE supplier_name = 'ABC Traders Pvt Ltd')
--     WHERE username = 'supplier1';
--   COMMIT;
-- ============================================================

-- ============================================================
-- Module 4 (Warehouse Management)
-- WH-01 Receive Goods, WH-02 Store Inventory, WH-03 Update Stock,
-- WH-04 Dispatch Goods, WH-05 Warehouse Reports
-- ============================================================

CREATE TABLE inventory (
    item_id           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_name         VARCHAR2(150) NOT NULL UNIQUE,
    quantity_on_hand  NUMBER(12) DEFAULT 0 NOT NULL,
    reorder_level     NUMBER(12) DEFAULT 0 NOT NULL,
    location          VARCHAR2(100),
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_transactions (
    txn_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id       NUMBER NOT NULL REFERENCES inventory(item_id),
    po_id         NUMBER REFERENCES purchase_orders(po_id),
    txn_type      VARCHAR2(20) NOT NULL
                  CONSTRAINT chk_txn_type CHECK (txn_type IN ('RECEIVE','DISPATCH','ADJUSTMENT')),
    quantity      NUMBER(12) NOT NULL,
    performed_by  VARCHAR2(50),
    remarks       VARCHAR2(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample inventory so Warehouse Reports has something to show immediately
INSERT INTO inventory (item_name, quantity_on_hand, reorder_level, location) VALUES
('Steel Rods (12mm)', 120, 100, 'Rack A1');
INSERT INTO inventory (item_name, quantity_on_hand, reorder_level, location) VALUES
('Packaging Boxes', 40, 150, 'Rack B3');

COMMIT;

-- ============================================================
-- MIGRATING AN EXISTING DATABASE for Module 4: if inventory /
-- inventory_transactions don't exist yet, just run the two CREATE TABLE
-- statements above (and the sample INSERTs if you want demo data).
-- ============================================================

-- ============================================================
-- Module 5 (Logistics Management)
-- LG-01 Assign Delivery, LG-02 Track Shipment,
-- LG-03 Update Delivery Status, LG-04 Confirm Delivery
--
-- Each shipment fulfils exactly one warehouse DISPATCH transaction --
-- goods only enter the Logistics pipeline once they've actually left
-- the warehouse.
-- ============================================================

CREATE TABLE shipments (
    shipment_id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    txn_id         NUMBER NOT NULL UNIQUE REFERENCES inventory_transactions(txn_id),
    destination    VARCHAR2(200) NOT NULL,
    carrier_name   VARCHAR2(100) NOT NULL,
    vehicle_no     VARCHAR2(50),
    status         VARCHAR2(20) DEFAULT 'ASSIGNED' NOT NULL
                   CONSTRAINT chk_shipment_status
                   CHECK (status IN ('ASSIGNED','IN_TRANSIT','DELIVERED')),
    assigned_by    VARCHAR2(50),
    assigned_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    in_transit_at  TIMESTAMP,
    delivered_at   TIMESTAMP,
    remarks        VARCHAR2(255)
);

-- ============================================================
-- MIGRATING AN EXISTING DATABASE for Module 5: if shipments doesn't
-- exist yet, just run the CREATE TABLE statement above.
-- ============================================================

-- ============================================================
-- Monitor System (Admin): login audit trail
-- Every login attempt (successful or not) is recorded so the Monitor
-- System page can show recent activity and flag failed attempts.
-- ============================================================

CREATE TABLE login_audit (
    audit_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) NOT NULL,
    success       CHAR(1) NOT NULL CHECK (success IN ('Y','N')),
    ip_address    VARCHAR2(50),
    attempted_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- MIGRATING AN EXISTING DATABASE for Monitor System: if login_audit
-- doesn't exist yet, just run the CREATE TABLE statement above.
-- ============================================================
