-- ============================================================
-- Supply Chain Management System - Module 1 (Login Dashboard)
-- Database: Oracle XE 21.3
-- ============================================================
-- Run this as SYS or SYSTEM (e.g. in SQL*Plus, SQLcl, or SQL Developer)
-- connected to the CDB, or adjust to run inside XEPDB1 directly.
-- ============================================================

-- Step 1: create a dedicated schema/user for the app
-- (skip this block if scms_user already exists)
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER scms_user IDENTIFIED BY scms_pass;
GRANT CONNECT, RESOURCE TO scms_user;
GRANT CREATE SESSION TO scms_user;
ALTER USER scms_user QUOTA UNLIMITED ON USERS;

-- Step 2: connect as scms_user before running the rest
-- (in SQL*Plus:  CONNECT scms_user/scms_pass@localhost:1521/XEPDB1)

CREATE TABLE users (
    user_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(50)  NOT NULL UNIQUE,
    password     VARCHAR2(256) NOT NULL,          -- SHA-256 hashed password
    full_name    VARCHAR2(100) NOT NULL,
    email        VARCHAR2(100),
    role         VARCHAR2(30)  NOT NULL
                 CHECK (role IN ('ADMIN','PROCUREMENT_MANAGER','WAREHOUSE_MANAGER',
                                  'SUPPLIER','LOGISTICS_STAFF')),
    status       VARCHAR2(10) DEFAULT 'ACTIVE'
                 CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Sample users (password for ALL of them is: Passw0rd!)
-- SHA-256("Passw0rd!") =
-- e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee
-- (generated by PasswordUtil.hashPassword; see util package)
-- ============================================================
INSERT INTO users (username, password, full_name, email, role) VALUES
('admin1',       'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'System Administrator', 'admin@scms.com',        'ADMIN');
INSERT INTO users (username, password, full_name, email, role) VALUES
('proc_mgr1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Ravi Kumar',           'proc@scms.com',         'PROCUREMENT_MANAGER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('wh_mgr1',      'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Suresh Babu',          'warehouse@scms.com',    'WAREHOUSE_MANAGER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('supplier1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'ABC Traders Pvt Ltd',  'supplier@scms.com',     'SUPPLIER');
INSERT INTO users (username, password, full_name, email, role) VALUES
('logistics1',   'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Karthik Raja',         'logistics@scms.com',    'LOGISTICS_STAFF');

COMMIT;

-- ============================================================
-- Module 2 (Supplier Management)
-- SRS section 6 - Supplier_ID, Supplier_Name, Contact_No, Email, Address
-- ============================================================

CREATE TABLE suppliers (
    supplier_id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    supplier_name  VARCHAR2(150) NOT NULL,
    contact_no     VARCHAR2(20)  NOT NULL,
    email          VARCHAR2(100),
    address        VARCHAR2(255),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample suppliers
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('ABC Traders Pvt Ltd',   '9876543210', 'contact@abctraders.com',    'No. 12, Anna Salai, Chennai');
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('Global Steel Supplies', '9123456780', 'sales@globalsteel.com',     'Plot 7, Industrial Estate, Coimbatore');
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('Prime Packaging Co.',   '9988776655', 'info@primepackaging.com',   '45 Market Road, Madurai');

COMMIT;
