-- ============================================================
-- Supply Chain Management System - Module 1 (Login Dashboard)
-- Database: MySQL
-- ============================================================

CREATE DATABASE IF NOT EXISTS scms_db;
USE scms_db;

CREATE TABLE IF NOT EXISTS users (
    user_id      INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    password     VARCHAR(256) NOT NULL,           -- SHA-256 hashed password
    full_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(100),
    role         ENUM('ADMIN','PROCUREMENT_MANAGER','WAREHOUSE_MANAGER',
                       'SUPPLIER','LOGISTICS_STAFF') NOT NULL,
    status       ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Sample users (password for ALL of them is: Passw0rd!)
-- SHA-256("Passw0rd!") =
-- e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee
-- (generated by PasswordUtil.hashPassword; see util package)
-- ============================================================
INSERT INTO users (username, password, full_name, email, role) VALUES
('admin1',       'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'System Administrator', 'admin@scms.com',        'ADMIN'),
('proc_mgr1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Ravi Kumar',           'proc@scms.com',         'PROCUREMENT_MANAGER'),
('wh_mgr1',      'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Suresh Babu',          'warehouse@scms.com',    'WAREHOUSE_MANAGER'),
('supplier1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'ABC Traders Pvt Ltd',  'supplier@scms.com',     'SUPPLIER'),
('logistics1',   'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Karthik Raja',         'logistics@scms.com',    'LOGISTICS_STAFF');
