-- ============================================================
-- Supply Chain Management System - Module 1 (Login Dashboard)
-- Database: MySQL
-- ============================================================

CREATE DATABASE IF NOT EXISTS scms_db;
USE scms_db;

CREATE TABLE IF NOT EXISTS users (
    user_id      INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    password     VARCHAR(256) NOT NULL,           -- SHA-256 hashed password
    full_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(100),
    role         ENUM('ADMIN','PROCUREMENT_MANAGER','WAREHOUSE_MANAGER',
                       'SUPPLIER','LOGISTICS_STAFF') NOT NULL,
    status       ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Sample users (password for ALL of them is: Passw0rd!)
-- SHA-256("Passw0rd!") =
-- e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee
-- (generated by PasswordUtil.hashPassword; see util package)
-- ============================================================
INSERT INTO users (username, password, full_name, email, role) VALUES
('admin1',       'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'System Administrator', 'admin@scms.com',        'ADMIN'),
('proc_mgr1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Ravi Kumar',           'proc@scms.com',         'PROCUREMENT_MANAGER'),
('wh_mgr1',      'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Suresh Babu',          'warehouse@scms.com',    'WAREHOUSE_MANAGER'),
('supplier1',    'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'ABC Traders Pvt Ltd',  'supplier@scms.com',     'SUPPLIER'),
('logistics1',   'e66860546f18cdbbcd86b35e18b525bffc67f772c650cedfe3ff7a0026fa1dee', 'Karthik Raja',         'logistics@scms.com',    'LOGISTICS_STAFF');

-- ============================================================
-- Module 2 (Supplier Management)
-- ============================================================

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id    INT AUTO_INCREMENT PRIMARY KEY,
    supplier_name  VARCHAR(150) NOT NULL,
    contact_no     VARCHAR(20)  NOT NULL,
    email          VARCHAR(100),
    address        VARCHAR(255),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample suppliers
INSERT INTO suppliers (supplier_name, contact_no, email, address) VALUES
('ABC Traders Pvt Ltd',   '9876543210', 'contact@abctraders.com',    'No. 12, Anna Salai, Chennai'),
('Global Steel Supplies', '9123456780', 'sales@globalsteel.com',     'Plot 7, Industrial Estate, Coimbatore'),
('Prime Packaging Co.',   '9988776655', 'info@primepackaging.com',   '45 Market Road, Madurai');

-- ============================================================
-- Module 3 (Procurement Management) - Purchase Orders
-- PO-01 Create, PO-02 Approve, PO-03 Cancel, PO-04 Track Status,
-- PO-05 Supplier Performance, PO-06 Reports
-- ============================================================

CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id          INT AUTO_INCREMENT PRIMARY KEY,
    supplier_id    INT NOT NULL,
    item_name      VARCHAR(150) NOT NULL,
    quantity       INT NOT NULL,
    unit_price     DECIMAL(12,2) NOT NULL,
    total_amount   DECIMAL(14,2) NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_by     VARCHAR(50),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by    VARCHAR(50),
    approved_at    TIMESTAMP NULL,
    shipped_at     TIMESTAMP NULL,
    delivered_at   TIMESTAMP NULL,
    remarks        VARCHAR(255),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

-- Sample purchase orders
INSERT INTO purchase_orders (supplier_id, item_name, quantity, unit_price, total_amount, status, created_by) VALUES
(1, 'Steel Rods (12mm)', 500, 65.00, 32500.00, 'APPROVED', 'admin1'),
(2, 'Packaging Boxes',   2000, 12.50, 25000.00, 'PENDING', 'proc_mgr1'),
(3, 'Industrial Gloves', 1000, 45.00, 45000.00, 'CANCELLED', 'proc_mgr1');

-- ============================================================
-- Links a SUPPLIER-role login to the supplier company record they
-- represent, so the Supplier Portal knows whose orders to show.
-- NULL for every other role.
--
-- If you already ran an earlier version of this script, just run these
-- two statements against your existing database:
--   ALTER TABLE purchase_orders ADD COLUMN shipped_at TIMESTAMP NULL;
--   ALTER TABLE purchase_orders ADD COLUMN delivered_at TIMESTAMP NULL;
--   ALTER TABLE users ADD COLUMN supplier_id INT NULL,
--     ADD FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id);
-- ============================================================

ALTER TABLE users ADD COLUMN supplier_id INT NULL,
    ADD FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id);

UPDATE users SET supplier_id = (SELECT supplier_id FROM suppliers WHERE supplier_name = 'ABC Traders Pvt Ltd')
WHERE username = 'supplier1';

-- ============================================================
-- Module 4 (Warehouse Management)
-- WH-01 Receive Goods, WH-02 Store Inventory, WH-03 Update Stock,
-- WH-04 Dispatch Goods, WH-05 Warehouse Reports
-- ============================================================

CREATE TABLE IF NOT EXISTS inventory (
    item_id           INT AUTO_INCREMENT PRIMARY KEY,
    item_name         VARCHAR(150) NOT NULL UNIQUE,
    quantity_on_hand  INT NOT NULL DEFAULT 0,
    reorder_level     INT NOT NULL DEFAULT 0,
    location          VARCHAR(100),
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
    txn_id        INT AUTO_INCREMENT PRIMARY KEY,
    item_id       INT NOT NULL,
    po_id         INT NULL,
    txn_type      VARCHAR(20) NOT NULL,
    quantity      INT NOT NULL,
    performed_by  VARCHAR(50),
    remarks       VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES inventory(item_id),
    FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id)
);

-- Sample inventory so Warehouse Reports has something to show immediately
INSERT INTO inventory (item_name, quantity_on_hand, reorder_level, location) VALUES
('Steel Rods (12mm)', 120, 100, 'Rack A1'),
('Packaging Boxes', 40, 150, 'Rack B3');
